swagger: "2.0"
info:
  version: "0.0.1"
  title: Schedule API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /schedule/event/{sellerId}:
    # binds a127 app logic to a route
    x-swagger-router-controller: schedule
    get:
      tags:
        - "schedule"
      description: Returns 'Schedule' of Seller
      operationId: getSchedule
      parameters:
        - name: sellerId
          in: path
          description: The schedule of the seller
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ScheduleResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - "schedule"
      summary: "Returns 'Schedule' of Seller"
      operationId: "addSchedule"
      parameters:
        - name: "sellerId"
          in: "path"
          description: "The schedule of the seller"
          required: true
          type: string
        - name: "body"
          in: "body"
          required: false
          schema:
            $ref: "#/definitions/Schedule"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/ScheduleResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags:
        - "schedule"
      summary: "Returns 'Schedule' of Seller"
      operationId: "updateSchedule"
      parameters:
        - name: "sellerId"
          in: "path"
          description: "The schedule of the seller"
          required: true
          type: string
        - name: "body"
          in: "body"
          required: false
          schema:
            $ref: "#/definitions/Schedule"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/ScheduleResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /schedule/event/{sellerId}/{eventId}:
    x-swagger-router-controller: schedule
    delete:
      tags:
        - "schedule"
      summary: "Returns 'Schedule' of Seller"
      operationId: "disableSchedule"
      parameters:
        - name: "sellerId"
          in: "path"
          description: "The schedule of the seller"
          required: true
          type: string
        - name: "eventId"
          in: "path"
          description: "The schedule of the seller"
          required: true
          type: string
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/ScheduleResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Schedule:
    type: "object"
    properties:
      id:
        type: "string"
      startTime:
        type: "string"
        default: "2017-12-31T00:00:01.01Z"
      endTime:
        type: "string"
        default: "2017-12-31T23:59:59.59Z"
      event:
        type: "string"
        default: lack_of_delivery_staff
        enum:
          - lack_of_delivery_staff
          - connection issues
          - overloaded
          - holidays
    xml:
      name: "Schedule"
  ScheduleResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
